#if !canImport(ObjectiveC)
import XCTest

extension BinaryParserTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryParserTest = [
        ("testReadAndWrite", testReadAndWrite),
    ]
}

extension IndexedDataTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IndexedDataTest = [
        ("testReadAndWrite", testReadAndWrite),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BinaryParserTest.__allTests__BinaryParserTest),
        testCase(IndexedDataTest.__allTests__IndexedDataTest),
    ]
}
#endif
